//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsProductOferta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsProductOfertaSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsProductOferta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsProductOfertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsProductOferta() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsProductOferta_WS_LE_ConsProductOferta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsProductOfertCompletedEventHandler ConsProductOfertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsProductOfert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsProductOferta[] ConsProductOfert(string quoteid) {
            object[] results = this.Invoke("ConsProductOfert", new object[] {
                        quoteid});
            return ((CsProductOferta[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsProductOfertAsync(string quoteid) {
            this.ConsProductOfertAsync(quoteid, null);
        }
        
        /// <remarks/>
        public void ConsProductOfertAsync(string quoteid, object userState) {
            if ((this.ConsProductOfertOperationCompleted == null)) {
                this.ConsProductOfertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsProductOfertOperationCompleted);
            }
            this.InvokeAsync("ConsProductOfert", new object[] {
                        quoteid}, this.ConsProductOfertOperationCompleted, userState);
        }
        
        private void OnConsProductOfertOperationCompleted(object arg) {
            if ((this.ConsProductOfertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsProductOfertCompleted(this, new ConsProductOfertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsProductOferta {
        
        private string quotedetailidField;
        
        private string quoteidField;
        
        private string udem_programaacademico_idField;
        
        private string udem_programaacademico_nameField;
        
        private string udem_le_creditosporproductoField;
        
        private string udem_le_semestresporproductoField;
        
        private string product_idField;
        
        private string product_nameField;
        
        private string uom_idField;
        
        private string uom_nameField;
        
        private string udem_tipodeperiodoField;
        
        private string udem_unidadacotizarField;
        
        private string udem_cantidadacotizarField;
        
        private string udem_le_porcentajebecaField;
        
        private string udem_le_semestrestotalesField;
        
        private string quantityField;
        
        private string priceperunitField;
        
        private string baseamountField;
        
        private string new_unidadudem_idField;
        
        private string new_unidadudem_nameField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string quotedetailid {
            get {
                return this.quotedetailidField;
            }
            set {
                this.quotedetailidField = value;
            }
        }
        
        /// <remarks/>
        public string quoteid {
            get {
                return this.quoteidField;
            }
            set {
                this.quoteidField = value;
            }
        }
        
        /// <remarks/>
        public string udem_programaacademico_id {
            get {
                return this.udem_programaacademico_idField;
            }
            set {
                this.udem_programaacademico_idField = value;
            }
        }
        
        /// <remarks/>
        public string udem_programaacademico_name {
            get {
                return this.udem_programaacademico_nameField;
            }
            set {
                this.udem_programaacademico_nameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_le_creditosporproducto {
            get {
                return this.udem_le_creditosporproductoField;
            }
            set {
                this.udem_le_creditosporproductoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_le_semestresporproducto {
            get {
                return this.udem_le_semestresporproductoField;
            }
            set {
                this.udem_le_semestresporproductoField = value;
            }
        }
        
        /// <remarks/>
        public string product_id {
            get {
                return this.product_idField;
            }
            set {
                this.product_idField = value;
            }
        }
        
        /// <remarks/>
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                this.product_nameField = value;
            }
        }
        
        /// <remarks/>
        public string uom_id {
            get {
                return this.uom_idField;
            }
            set {
                this.uom_idField = value;
            }
        }
        
        /// <remarks/>
        public string uom_name {
            get {
                return this.uom_nameField;
            }
            set {
                this.uom_nameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_tipodeperiodo {
            get {
                return this.udem_tipodeperiodoField;
            }
            set {
                this.udem_tipodeperiodoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_unidadacotizar {
            get {
                return this.udem_unidadacotizarField;
            }
            set {
                this.udem_unidadacotizarField = value;
            }
        }
        
        /// <remarks/>
        public string udem_cantidadacotizar {
            get {
                return this.udem_cantidadacotizarField;
            }
            set {
                this.udem_cantidadacotizarField = value;
            }
        }
        
        /// <remarks/>
        public string udem_le_porcentajebeca {
            get {
                return this.udem_le_porcentajebecaField;
            }
            set {
                this.udem_le_porcentajebecaField = value;
            }
        }
        
        /// <remarks/>
        public string udem_le_semestrestotales {
            get {
                return this.udem_le_semestrestotalesField;
            }
            set {
                this.udem_le_semestrestotalesField = value;
            }
        }
        
        /// <remarks/>
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string priceperunit {
            get {
                return this.priceperunitField;
            }
            set {
                this.priceperunitField = value;
            }
        }
        
        /// <remarks/>
        public string baseamount {
            get {
                return this.baseamountField;
            }
            set {
                this.baseamountField = value;
            }
        }
        
        /// <remarks/>
        public string new_unidadudem_id {
            get {
                return this.new_unidadudem_idField;
            }
            set {
                this.new_unidadudem_idField = value;
            }
        }
        
        /// <remarks/>
        public string new_unidadudem_name {
            get {
                return this.new_unidadudem_nameField;
            }
            set {
                this.new_unidadudem_nameField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConsProductOfertCompletedEventHandler(object sender, ConsProductOfertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsProductOfertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsProductOfertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsProductOferta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsProductOferta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591