//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsCP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsCPSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsCP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConscpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConscpAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsCP() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsCP_WS_LE_ConsCP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConscpCompletedEventHandler ConscpCompleted;
        
        /// <remarks/>
        public event ConscpACompletedEventHandler ConscpACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Conscp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CPConsulta[] Conscp(string CP) {
            object[] results = this.Invoke("Conscp", new object[] {
                        CP});
            return ((CPConsulta[])(results[0]));
        }
        
        /// <remarks/>
        public void ConscpAsync(string CP) {
            this.ConscpAsync(CP, null);
        }
        
        /// <remarks/>
        public void ConscpAsync(string CP, object userState) {
            if ((this.ConscpOperationCompleted == null)) {
                this.ConscpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConscpOperationCompleted);
            }
            this.InvokeAsync("Conscp", new object[] {
                        CP}, this.ConscpOperationCompleted, userState);
        }
        
        private void OnConscpOperationCompleted(object arg) {
            if ((this.ConscpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConscpCompleted(this, new ConscpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConscpA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CPConsulta[] ConscpA(string CP, string Asesor) {
            object[] results = this.Invoke("ConscpA", new object[] {
                        CP,
                        Asesor});
            return ((CPConsulta[])(results[0]));
        }
        
        /// <remarks/>
        public void ConscpAAsync(string CP, string Asesor) {
            this.ConscpAAsync(CP, Asesor, null);
        }
        
        /// <remarks/>
        public void ConscpAAsync(string CP, string Asesor, object userState) {
            if ((this.ConscpAOperationCompleted == null)) {
                this.ConscpAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConscpAOperationCompleted);
            }
            this.InvokeAsync("ConscpA", new object[] {
                        CP,
                        Asesor}, this.ConscpAOperationCompleted, userState);
        }
        
        private void OnConscpAOperationCompleted(object arg) {
            if ((this.ConscpACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConscpACompleted(this, new ConscpACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CPConsulta {
        
        private string recr_alcaldiaomunicipioField;
        
        private string recr_ciudadField;
        
        private string recr_coloniaField;
        
        private string recr_estadoField;
        
        private string recr_nameField;
        
        private string recr_paisField;
        
        private string recr_zonaField;
        
        private string recr_asentamientoField;
        
        private string mensajesField;
        
        /// <remarks/>
        public string recr_alcaldiaomunicipio {
            get {
                return this.recr_alcaldiaomunicipioField;
            }
            set {
                this.recr_alcaldiaomunicipioField = value;
            }
        }
        
        /// <remarks/>
        public string recr_ciudad {
            get {
                return this.recr_ciudadField;
            }
            set {
                this.recr_ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string recr_colonia {
            get {
                return this.recr_coloniaField;
            }
            set {
                this.recr_coloniaField = value;
            }
        }
        
        /// <remarks/>
        public string recr_estado {
            get {
                return this.recr_estadoField;
            }
            set {
                this.recr_estadoField = value;
            }
        }
        
        /// <remarks/>
        public string recr_name {
            get {
                return this.recr_nameField;
            }
            set {
                this.recr_nameField = value;
            }
        }
        
        /// <remarks/>
        public string recr_pais {
            get {
                return this.recr_paisField;
            }
            set {
                this.recr_paisField = value;
            }
        }
        
        /// <remarks/>
        public string recr_zona {
            get {
                return this.recr_zonaField;
            }
            set {
                this.recr_zonaField = value;
            }
        }
        
        /// <remarks/>
        public string recr_asentamiento {
            get {
                return this.recr_asentamientoField;
            }
            set {
                this.recr_asentamientoField = value;
            }
        }
        
        /// <remarks/>
        public string mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConscpCompletedEventHandler(object sender, ConscpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConscpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConscpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CPConsulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CPConsulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConscpACompletedEventHandler(object sender, ConscpACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConscpACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConscpACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CPConsulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CPConsulta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591