//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ProgramaAcademico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ProgramaAcademicoSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ProgramaAcademico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsProgramaAcademicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsProgramaAcademicoGuidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ProgramaAcademico() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ProgramaAcademico_WS_LE_ProgramaAcademico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsProgramaAcademicoCompletedEventHandler ConsProgramaAcademicoCompleted;
        
        /// <remarks/>
        public event ConsProgramaAcademicoGuidCompletedEventHandler ConsProgramaAcademicoGuidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsProgramaAcademico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsProgramaAcademico[] ConsProgramaAcademico(string disponibleLE) {
            object[] results = this.Invoke("ConsProgramaAcademico", new object[] {
                        disponibleLE});
            return ((CsProgramaAcademico[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsProgramaAcademicoAsync(string disponibleLE) {
            this.ConsProgramaAcademicoAsync(disponibleLE, null);
        }
        
        /// <remarks/>
        public void ConsProgramaAcademicoAsync(string disponibleLE, object userState) {
            if ((this.ConsProgramaAcademicoOperationCompleted == null)) {
                this.ConsProgramaAcademicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsProgramaAcademicoOperationCompleted);
            }
            this.InvokeAsync("ConsProgramaAcademico", new object[] {
                        disponibleLE}, this.ConsProgramaAcademicoOperationCompleted, userState);
        }
        
        private void OnConsProgramaAcademicoOperationCompleted(object arg) {
            if ((this.ConsProgramaAcademicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsProgramaAcademicoCompleted(this, new ConsProgramaAcademicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsProgramaAcademicoGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsProgramaAcademico[] ConsProgramaAcademicoGuid(string disponibleLE, string new_programaacademicoid) {
            object[] results = this.Invoke("ConsProgramaAcademicoGuid", new object[] {
                        disponibleLE,
                        new_programaacademicoid});
            return ((CsProgramaAcademico[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsProgramaAcademicoGuidAsync(string disponibleLE, string new_programaacademicoid) {
            this.ConsProgramaAcademicoGuidAsync(disponibleLE, new_programaacademicoid, null);
        }
        
        /// <remarks/>
        public void ConsProgramaAcademicoGuidAsync(string disponibleLE, string new_programaacademicoid, object userState) {
            if ((this.ConsProgramaAcademicoGuidOperationCompleted == null)) {
                this.ConsProgramaAcademicoGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsProgramaAcademicoGuidOperationCompleted);
            }
            this.InvokeAsync("ConsProgramaAcademicoGuid", new object[] {
                        disponibleLE,
                        new_programaacademicoid}, this.ConsProgramaAcademicoGuidOperationCompleted, userState);
        }
        
        private void OnConsProgramaAcademicoGuidOperationCompleted(object arg) {
            if ((this.ConsProgramaAcademicoGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsProgramaAcademicoGuidCompleted(this, new ConsProgramaAcademicoGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsProgramaAcademico {
        
        private string new_programaacademicoidField;
        
        private string new_programaField;
        
        private string new_siglasField;
        
        private string new_nivelacademico_idField;
        
        private string new_nivelacademico_nameField;
        
        private string new_division_idField;
        
        private string new_division_nameField;
        
        private string recr_campusidField;
        
        private string recr_campus_nameField;
        
        private string udem_disponibleleField;
        
        private string udem_creditosporprogramaField;
        
        private string udem_semestresporprogramaField;
        
        private string udem_tipodeperiodoField;
        
        private string udem_productorelacionado_idField;
        
        private string udem_productorelacionado_nameField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string new_programaacademicoid {
            get {
                return this.new_programaacademicoidField;
            }
            set {
                this.new_programaacademicoidField = value;
            }
        }
        
        /// <remarks/>
        public string new_programa {
            get {
                return this.new_programaField;
            }
            set {
                this.new_programaField = value;
            }
        }
        
        /// <remarks/>
        public string new_siglas {
            get {
                return this.new_siglasField;
            }
            set {
                this.new_siglasField = value;
            }
        }
        
        /// <remarks/>
        public string new_nivelacademico_id {
            get {
                return this.new_nivelacademico_idField;
            }
            set {
                this.new_nivelacademico_idField = value;
            }
        }
        
        /// <remarks/>
        public string new_nivelacademico_name {
            get {
                return this.new_nivelacademico_nameField;
            }
            set {
                this.new_nivelacademico_nameField = value;
            }
        }
        
        /// <remarks/>
        public string new_division_id {
            get {
                return this.new_division_idField;
            }
            set {
                this.new_division_idField = value;
            }
        }
        
        /// <remarks/>
        public string new_division_name {
            get {
                return this.new_division_nameField;
            }
            set {
                this.new_division_nameField = value;
            }
        }
        
        /// <remarks/>
        public string recr_campusid {
            get {
                return this.recr_campusidField;
            }
            set {
                this.recr_campusidField = value;
            }
        }
        
        /// <remarks/>
        public string recr_campus_name {
            get {
                return this.recr_campus_nameField;
            }
            set {
                this.recr_campus_nameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_disponiblele {
            get {
                return this.udem_disponibleleField;
            }
            set {
                this.udem_disponibleleField = value;
            }
        }
        
        /// <remarks/>
        public string udem_creditosporprograma {
            get {
                return this.udem_creditosporprogramaField;
            }
            set {
                this.udem_creditosporprogramaField = value;
            }
        }
        
        /// <remarks/>
        public string udem_semestresporprograma {
            get {
                return this.udem_semestresporprogramaField;
            }
            set {
                this.udem_semestresporprogramaField = value;
            }
        }
        
        /// <remarks/>
        public string udem_tipodeperiodo {
            get {
                return this.udem_tipodeperiodoField;
            }
            set {
                this.udem_tipodeperiodoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_productorelacionado_id {
            get {
                return this.udem_productorelacionado_idField;
            }
            set {
                this.udem_productorelacionado_idField = value;
            }
        }
        
        /// <remarks/>
        public string udem_productorelacionado_name {
            get {
                return this.udem_productorelacionado_nameField;
            }
            set {
                this.udem_productorelacionado_nameField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsProgramaAcademicoCompletedEventHandler(object sender, ConsProgramaAcademicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsProgramaAcademicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsProgramaAcademicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsProgramaAcademico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsProgramaAcademico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsProgramaAcademicoGuidCompletedEventHandler(object sender, ConsProgramaAcademicoGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsProgramaAcademicoGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsProgramaAcademicoGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsProgramaAcademico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsProgramaAcademico[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591