//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLegadoEducativo02.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConClientePotencial.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConClientePotencial_WS_LE_ConClientePotencial {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConClientePotencial_WS_LE_ConClientePotencial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsCP.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsCP_WS_LE_ConsCP {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsCP_WS_LE_ConsCP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsEscuelaCuenta.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsEscuelaCuenta_WS_LE_ConsEscuelaCuenta {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsEscuelaCuenta_WS_LE_ConsEscuelaCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsNivelAcademico.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsNivelAcademico_WS_LE_ConsNivelAcademico {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsNivelAcademico_WS_LE_ConsNivelAcademico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsUsuext.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsUsuext_WS_LE_ConsUsuext {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsUsuext_WS_LE_ConsUsuext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsUnidadUDEM.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsUnidadUDEM_WS_LE_ConsUnidadUDEM {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsUnidadUDEM_WS_LE_ConsUnidadUDEM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_InsertaFamilia_LE/" +
            "WS_LE_InsertaFamilia.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaFamilia_WS_LE_InsertaFamilia {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaFamilia_WS_LE_InsertaFamilia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_Contactos_LE/WS_LE" +
            "_InsertaContactos.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaContactos_WS_LE_InsertaContactos {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaContactos_WS_LE_InsertaContactos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_DatosFiscalesConta" +
            "cto_LE/WS_LE_InsertaDatosFiscalesContacto.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaDatosFiscalesContacto_WS_LE_InsertaDatosFiscalesContacto {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaDatosFiscalesContacto_WS_LE_InsertaDatosFiscale" +
                    "sContacto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_Oportunidad_LE/WS_" +
            "LE_Oportunidad.asmx")]
        public string WebLegadoEducativo02_WS_LE_Oportunidad_WS_LE_Oportunidad {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_Oportunidad_WS_LE_Oportunidad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsSolicitudCompra.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsSolicitudCompra_WS_LE_ConsSolicitudCompra {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsSolicitudCompra_WS_LE_ConsSolicitudCompra"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsFamiliaContacto.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsFamiliaContacto_WS_LE_ConsFamiliaContacto {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsFamiliaContacto_WS_LE_ConsFamiliaContacto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsDatosFiscales.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsDatosFiscales_WS_LE_ConsDatosFiscales {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsDatosFiscales_WS_LE_ConsDatosFiscales"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsBeneficiario.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsBeneficiario_WS_LE_ConsBeneficiario {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsBeneficiario_WS_LE_ConsBeneficiario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_Beneficiarios_LE/W" +
            "S_LE_Beneficiarios.asmx")]
        public string WebLegadoEducativo02_WS_LE_Beneficiarios_WS_LE_Beneficiarios {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_Beneficiarios_WS_LE_Beneficiarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsultaContac.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsultaContac_WS_LE_ConsultaContac {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsultaContac_WS_LE_ConsultaContac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsProducto.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsProducto_WS_LE_ConsProducto {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsProducto_WS_LE_ConsProducto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ListaDePrecios.asmx")]
        public string WebLegadoEducativo02_WS_LE_ListaDePrecios_WS_LE_ListaDePrecios {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ListaDePrecios_WS_LE_ListaDePrecios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsOferta.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsOferta_WS_LE_ConsOferta {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsOferta_WS_LE_ConsOferta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ProgramaAcademico.asmx")]
        public string WebLegadoEducativo02_WS_LE_ProgramaAcademico_WS_LE_ProgramaAcademico {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ProgramaAcademico_WS_LE_ProgramaAcademico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_Cotizaciones_LE/WS" +
            "_LE_Cotizaciones.asmx")]
        public string WebLegadoEducativo02_WS_LE_Cotizaciones_WS_LE_Cotizaciones {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_Cotizaciones_WS_LE_Cotizaciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsProductOferta.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsProductOferta_WS_LE_ConsProductOferta {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsProductOferta_WS_LE_ConsProductOferta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_SolicitudCompra_LE" +
            "/WS_LE_InsertaSolicitudCom.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaSolicitudCom_WS_LE_InsertaSolicitudCom {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaSolicitudCom_WS_LE_InsertaSolicitudCom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://eventosudemtst.udem.edu.mx:8087/UDEMDESA/LegadoEducativo/WS_LegadoEducativ" +
            "o/WS_LE_InsUsuarioExterno.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsUsuarioExterno_WS_LE_InsUsuarioExterno {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsUsuarioExterno_WS_LE_InsUsuarioExterno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_LegadoEducativo/WS" +
            "_LE_ConsFuenteLead.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsFuenteLead_WS_LE_ConsFuenteLead {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsFuenteLead_WS_LE_ConsFuenteLead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eventosudemtst.udem.edu.mx/UDEMDESA/LegadoEducativo/WS_ClientePotencial_L" +
            "E/WS_LE_InsertaClientePotencial.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaClientePotencial_WS_LE_InsertaClientePotencial {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaClientePotencial_WS_LE_InsertaClientePotencial"]));
            }
        }
    }
}
