//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_Documentos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_DocumentosSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_Documentos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InSuplementalSubOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_Documentos() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_Documentos_WS_LE_Documentos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InSuplementalSubCompletedEventHandler InSuplementalSubCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InSuplementalSub", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta InSuplementalSub(string new_supplementalinfosubmissionid, string new_contactoid, string new_solicitudid, string new_supplementalinfoitemid, string recr_revisadodaes, string new_revisadole, string new_submissiondate, string statuscode, string new_admisionestatus, string new_externallocation, string new_webexternaldescription, string Comentarios) {
            object[] results = this.Invoke("InSuplementalSub", new object[] {
                        new_supplementalinfosubmissionid,
                        new_contactoid,
                        new_solicitudid,
                        new_supplementalinfoitemid,
                        recr_revisadodaes,
                        new_revisadole,
                        new_submissiondate,
                        statuscode,
                        new_admisionestatus,
                        new_externallocation,
                        new_webexternaldescription,
                        Comentarios});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void InSuplementalSubAsync(string new_supplementalinfosubmissionid, string new_contactoid, string new_solicitudid, string new_supplementalinfoitemid, string recr_revisadodaes, string new_revisadole, string new_submissiondate, string statuscode, string new_admisionestatus, string new_externallocation, string new_webexternaldescription, string Comentarios) {
            this.InSuplementalSubAsync(new_supplementalinfosubmissionid, new_contactoid, new_solicitudid, new_supplementalinfoitemid, recr_revisadodaes, new_revisadole, new_submissiondate, statuscode, new_admisionestatus, new_externallocation, new_webexternaldescription, Comentarios, null);
        }
        
        /// <remarks/>
        public void InSuplementalSubAsync(string new_supplementalinfosubmissionid, string new_contactoid, string new_solicitudid, string new_supplementalinfoitemid, string recr_revisadodaes, string new_revisadole, string new_submissiondate, string statuscode, string new_admisionestatus, string new_externallocation, string new_webexternaldescription, string Comentarios, object userState) {
            if ((this.InSuplementalSubOperationCompleted == null)) {
                this.InSuplementalSubOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInSuplementalSubOperationCompleted);
            }
            this.InvokeAsync("InSuplementalSub", new object[] {
                        new_supplementalinfosubmissionid,
                        new_contactoid,
                        new_solicitudid,
                        new_supplementalinfoitemid,
                        recr_revisadodaes,
                        new_revisadole,
                        new_submissiondate,
                        statuscode,
                        new_admisionestatus,
                        new_externallocation,
                        new_webexternaldescription,
                        Comentarios}, this.InSuplementalSubOperationCompleted, userState);
        }
        
        private void OnInSuplementalSubOperationCompleted(object arg) {
            if ((this.InSuplementalSubCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InSuplementalSubCompleted(this, new InSuplementalSubCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string identificadorField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InSuplementalSubCompletedEventHandler(object sender, InSuplementalSubCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InSuplementalSubCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InSuplementalSubCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591