//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsBeneficiario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsBeneficiarioSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsBeneficiario : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConBeneficiarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConBeneficiarioGuidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsBeneficiario() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsBeneficiario_WS_LE_ConsBeneficiario;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConBeneficiarioCompletedEventHandler ConBeneficiarioCompleted;
        
        /// <remarks/>
        public event ConBeneficiarioGuidCompletedEventHandler ConBeneficiarioGuidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConBeneficiario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsBeneficiario[] ConBeneficiario(string solicitud) {
            object[] results = this.Invoke("ConBeneficiario", new object[] {
                        solicitud});
            return ((CsBeneficiario[])(results[0]));
        }
        
        /// <remarks/>
        public void ConBeneficiarioAsync(string solicitud) {
            this.ConBeneficiarioAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void ConBeneficiarioAsync(string solicitud, object userState) {
            if ((this.ConBeneficiarioOperationCompleted == null)) {
                this.ConBeneficiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConBeneficiarioOperationCompleted);
            }
            this.InvokeAsync("ConBeneficiario", new object[] {
                        solicitud}, this.ConBeneficiarioOperationCompleted, userState);
        }
        
        private void OnConBeneficiarioOperationCompleted(object arg) {
            if ((this.ConBeneficiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConBeneficiarioCompleted(this, new ConBeneficiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConBeneficiarioGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsBeneficiario[] ConBeneficiarioGuid(string solicitud, string guidBenefi) {
            object[] results = this.Invoke("ConBeneficiarioGuid", new object[] {
                        solicitud,
                        guidBenefi});
            return ((CsBeneficiario[])(results[0]));
        }
        
        /// <remarks/>
        public void ConBeneficiarioGuidAsync(string solicitud, string guidBenefi) {
            this.ConBeneficiarioGuidAsync(solicitud, guidBenefi, null);
        }
        
        /// <remarks/>
        public void ConBeneficiarioGuidAsync(string solicitud, string guidBenefi, object userState) {
            if ((this.ConBeneficiarioGuidOperationCompleted == null)) {
                this.ConBeneficiarioGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConBeneficiarioGuidOperationCompleted);
            }
            this.InvokeAsync("ConBeneficiarioGuid", new object[] {
                        solicitud,
                        guidBenefi}, this.ConBeneficiarioGuidOperationCompleted, userState);
        }
        
        private void OnConBeneficiarioGuidOperationCompleted(object arg) {
            if ((this.ConBeneficiarioGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConBeneficiarioGuidCompleted(this, new ConBeneficiarioGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsBeneficiario {
        
        private string udem_solicituddecompraField;
        
        private string udem_solicituddecompra_NameField;
        
        private string udem_beneficiariosidField;
        
        private string udem_beneficiarioField;
        
        private string udem_beneficiario_NameField;
        
        private string udem_nameField;
        
        private string udem_niveldeestudioField;
        
        private string udem_niveldeestudio_NameField;
        
        private string udem_escueladeprocedenciaField;
        
        private string udem_escueladeprocedencia_NameField;
        
        private string udem_carreranoudemField;
        
        private string udem_gradoField;
        
        private string udem_debecaField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string udem_solicituddecompra {
            get {
                return this.udem_solicituddecompraField;
            }
            set {
                this.udem_solicituddecompraField = value;
            }
        }
        
        /// <remarks/>
        public string udem_solicituddecompra_Name {
            get {
                return this.udem_solicituddecompra_NameField;
            }
            set {
                this.udem_solicituddecompra_NameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_beneficiariosid {
            get {
                return this.udem_beneficiariosidField;
            }
            set {
                this.udem_beneficiariosidField = value;
            }
        }
        
        /// <remarks/>
        public string udem_beneficiario {
            get {
                return this.udem_beneficiarioField;
            }
            set {
                this.udem_beneficiarioField = value;
            }
        }
        
        /// <remarks/>
        public string udem_beneficiario_Name {
            get {
                return this.udem_beneficiario_NameField;
            }
            set {
                this.udem_beneficiario_NameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_name {
            get {
                return this.udem_nameField;
            }
            set {
                this.udem_nameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_niveldeestudio {
            get {
                return this.udem_niveldeestudioField;
            }
            set {
                this.udem_niveldeestudioField = value;
            }
        }
        
        /// <remarks/>
        public string udem_niveldeestudio_Name {
            get {
                return this.udem_niveldeestudio_NameField;
            }
            set {
                this.udem_niveldeestudio_NameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_escueladeprocedencia {
            get {
                return this.udem_escueladeprocedenciaField;
            }
            set {
                this.udem_escueladeprocedenciaField = value;
            }
        }
        
        /// <remarks/>
        public string udem_escueladeprocedencia_Name {
            get {
                return this.udem_escueladeprocedencia_NameField;
            }
            set {
                this.udem_escueladeprocedencia_NameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_carreranoudem {
            get {
                return this.udem_carreranoudemField;
            }
            set {
                this.udem_carreranoudemField = value;
            }
        }
        
        /// <remarks/>
        public string udem_grado {
            get {
                return this.udem_gradoField;
            }
            set {
                this.udem_gradoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_debeca {
            get {
                return this.udem_debecaField;
            }
            set {
                this.udem_debecaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConBeneficiarioCompletedEventHandler(object sender, ConBeneficiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConBeneficiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConBeneficiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsBeneficiario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsBeneficiario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConBeneficiarioGuidCompletedEventHandler(object sender, ConBeneficiarioGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConBeneficiarioGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConBeneficiarioGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsBeneficiario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsBeneficiario[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591