//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsUnidadUDEM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsUnidadUDEMSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsUnidadUDEM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsUnidadUDEMOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsUnidadUDEM() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsUnidadUDEM_WS_LE_ConsUnidadUDEM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsUnidadUDEMCompletedEventHandler ConsUnidadUDEMCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsUnidadUDEM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsUnidadUDEM[] ConsUnidadUDEM(string nivel) {
            object[] results = this.Invoke("ConsUnidadUDEM", new object[] {
                        nivel});
            return ((CsUnidadUDEM[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsUnidadUDEMAsync(string nivel) {
            this.ConsUnidadUDEMAsync(nivel, null);
        }
        
        /// <remarks/>
        public void ConsUnidadUDEMAsync(string nivel, object userState) {
            if ((this.ConsUnidadUDEMOperationCompleted == null)) {
                this.ConsUnidadUDEMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsUnidadUDEMOperationCompleted);
            }
            this.InvokeAsync("ConsUnidadUDEM", new object[] {
                        nivel}, this.ConsUnidadUDEMOperationCompleted, userState);
        }
        
        private void OnConsUnidadUDEMOperationCompleted(object arg) {
            if ((this.ConsUnidadUDEMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsUnidadUDEMCompleted(this, new ConsUnidadUDEMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsUnidadUDEM {
        
        private string new_unidadudemidField;
        
        private string new_siglasField;
        
        private string new_nameField;
        
        private string recr_displayorderField;
        
        private string recr_nivelacademicoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string new_unidadudemid {
            get {
                return this.new_unidadudemidField;
            }
            set {
                this.new_unidadudemidField = value;
            }
        }
        
        /// <remarks/>
        public string new_siglas {
            get {
                return this.new_siglasField;
            }
            set {
                this.new_siglasField = value;
            }
        }
        
        /// <remarks/>
        public string new_name {
            get {
                return this.new_nameField;
            }
            set {
                this.new_nameField = value;
            }
        }
        
        /// <remarks/>
        public string recr_displayorder {
            get {
                return this.recr_displayorderField;
            }
            set {
                this.recr_displayorderField = value;
            }
        }
        
        /// <remarks/>
        public string recr_nivelacademico {
            get {
                return this.recr_nivelacademicoField;
            }
            set {
                this.recr_nivelacademicoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsUnidadUDEMCompletedEventHandler(object sender, ConsUnidadUDEMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsUnidadUDEMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsUnidadUDEMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsUnidadUDEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsUnidadUDEM[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591