//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsSolicitudCompra {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsSolicitudCompraSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsSolicitudCompra : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsSoliOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsSolicitudCompra() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsSolicitudCompra_WS_LE_ConsSolicitudCompra;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsSoliCompletedEventHandler ConsSoliCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsSoli", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RecuperaSolicitud[] ConsSoli(string titular) {
            object[] results = this.Invoke("ConsSoli", new object[] {
                        titular});
            return ((RecuperaSolicitud[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsSoliAsync(string titular) {
            this.ConsSoliAsync(titular, null);
        }
        
        /// <remarks/>
        public void ConsSoliAsync(string titular, object userState) {
            if ((this.ConsSoliOperationCompleted == null)) {
                this.ConsSoliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsSoliOperationCompleted);
            }
            this.InvokeAsync("ConsSoli", new object[] {
                        titular}, this.ConsSoliOperationCompleted, userState);
        }
        
        private void OnConsSoliOperationCompleted(object arg) {
            if ((this.ConsSoliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsSoliCompleted(this, new ConsSoliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaSolicitud {
        
        private string opportunityidField;
        
        private string udem_solicituddecompraidField;
        
        private string udem_nameField;
        
        private string udem_titularField;
        
        private string guid_udem_titularField;
        
        private string udem_titulardesignadoField;
        
        private string guid_udem_titulardesignadoField;
        
        private string udem_requiererecibofiscalField;
        
        private string udem_datosfiscalesField;
        
        private string guid_udem_datosfiscalesField;
        
        private string udem_documentosentregadostitularField;
        
        private string udem_documentosentregadostitulardesignadoField;
        
        private string udem_documentosentregadosbeneficiariosField;
        
        private string mensajeField;
        
        private RecuperaBenefi[] beneficiariosField;
        
        /// <remarks/>
        public string opportunityid {
            get {
                return this.opportunityidField;
            }
            set {
                this.opportunityidField = value;
            }
        }
        
        /// <remarks/>
        public string udem_solicituddecompraid {
            get {
                return this.udem_solicituddecompraidField;
            }
            set {
                this.udem_solicituddecompraidField = value;
            }
        }
        
        /// <remarks/>
        public string udem_name {
            get {
                return this.udem_nameField;
            }
            set {
                this.udem_nameField = value;
            }
        }
        
        /// <remarks/>
        public string udem_titular {
            get {
                return this.udem_titularField;
            }
            set {
                this.udem_titularField = value;
            }
        }
        
        /// <remarks/>
        public string Guid_udem_titular {
            get {
                return this.guid_udem_titularField;
            }
            set {
                this.guid_udem_titularField = value;
            }
        }
        
        /// <remarks/>
        public string udem_titulardesignado {
            get {
                return this.udem_titulardesignadoField;
            }
            set {
                this.udem_titulardesignadoField = value;
            }
        }
        
        /// <remarks/>
        public string Guid_udem_titulardesignado {
            get {
                return this.guid_udem_titulardesignadoField;
            }
            set {
                this.guid_udem_titulardesignadoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_requiererecibofiscal {
            get {
                return this.udem_requiererecibofiscalField;
            }
            set {
                this.udem_requiererecibofiscalField = value;
            }
        }
        
        /// <remarks/>
        public string udem_datosfiscales {
            get {
                return this.udem_datosfiscalesField;
            }
            set {
                this.udem_datosfiscalesField = value;
            }
        }
        
        /// <remarks/>
        public string Guid_udem_datosfiscales {
            get {
                return this.guid_udem_datosfiscalesField;
            }
            set {
                this.guid_udem_datosfiscalesField = value;
            }
        }
        
        /// <remarks/>
        public string udem_documentosentregadostitular {
            get {
                return this.udem_documentosentregadostitularField;
            }
            set {
                this.udem_documentosentregadostitularField = value;
            }
        }
        
        /// <remarks/>
        public string udem_documentosentregadostitulardesignado {
            get {
                return this.udem_documentosentregadostitulardesignadoField;
            }
            set {
                this.udem_documentosentregadostitulardesignadoField = value;
            }
        }
        
        /// <remarks/>
        public string udem_documentosentregadosbeneficiarios {
            get {
                return this.udem_documentosentregadosbeneficiariosField;
            }
            set {
                this.udem_documentosentregadosbeneficiariosField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public RecuperaBenefi[] Beneficiarios {
            get {
                return this.beneficiariosField;
            }
            set {
                this.beneficiariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperaBenefi {
        
        private string udem_beneficiarioField;
        
        private string udem_beneficiariosidField;
        
        /// <remarks/>
        public string udem_beneficiario {
            get {
                return this.udem_beneficiarioField;
            }
            set {
                this.udem_beneficiarioField = value;
            }
        }
        
        /// <remarks/>
        public string udem_beneficiariosid {
            get {
                return this.udem_beneficiariosidField;
            }
            set {
                this.udem_beneficiariosidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsSoliCompletedEventHandler(object sender, ConsSoliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsSoliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsSoliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RecuperaSolicitud[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RecuperaSolicitud[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591