//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsDatosFiscales {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsDatosFiscalesSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsDatosFiscales : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsDatosFiscalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsDatosFiscalesGuidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsDatosFiscales() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsDatosFiscales_WS_LE_ConsDatosFiscales;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsDatosFiscalesCompletedEventHandler ConsDatosFiscalesCompleted;
        
        /// <remarks/>
        public event ConsDatosFiscalesGuidCompletedEventHandler ConsDatosFiscalesGuidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsDatosFiscales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsDatosFiscales[] ConsDatosFiscales(string new_contacto) {
            object[] results = this.Invoke("ConsDatosFiscales", new object[] {
                        new_contacto});
            return ((CsDatosFiscales[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsDatosFiscalesAsync(string new_contacto) {
            this.ConsDatosFiscalesAsync(new_contacto, null);
        }
        
        /// <remarks/>
        public void ConsDatosFiscalesAsync(string new_contacto, object userState) {
            if ((this.ConsDatosFiscalesOperationCompleted == null)) {
                this.ConsDatosFiscalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsDatosFiscalesOperationCompleted);
            }
            this.InvokeAsync("ConsDatosFiscales", new object[] {
                        new_contacto}, this.ConsDatosFiscalesOperationCompleted, userState);
        }
        
        private void OnConsDatosFiscalesOperationCompleted(object arg) {
            if ((this.ConsDatosFiscalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsDatosFiscalesCompleted(this, new ConsDatosFiscalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsDatosFiscalesGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsDatosFiscales[] ConsDatosFiscalesGuid(string new_datosfiscalesdecontactoid) {
            object[] results = this.Invoke("ConsDatosFiscalesGuid", new object[] {
                        new_datosfiscalesdecontactoid});
            return ((CsDatosFiscales[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsDatosFiscalesGuidAsync(string new_datosfiscalesdecontactoid) {
            this.ConsDatosFiscalesGuidAsync(new_datosfiscalesdecontactoid, null);
        }
        
        /// <remarks/>
        public void ConsDatosFiscalesGuidAsync(string new_datosfiscalesdecontactoid, object userState) {
            if ((this.ConsDatosFiscalesGuidOperationCompleted == null)) {
                this.ConsDatosFiscalesGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsDatosFiscalesGuidOperationCompleted);
            }
            this.InvokeAsync("ConsDatosFiscalesGuid", new object[] {
                        new_datosfiscalesdecontactoid}, this.ConsDatosFiscalesGuidOperationCompleted, userState);
        }
        
        private void OnConsDatosFiscalesGuidOperationCompleted(object arg) {
            if ((this.ConsDatosFiscalesGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsDatosFiscalesGuidCompleted(this, new ConsDatosFiscalesGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsDatosFiscales {
        
        private string new_datosfiscalesdecontactoidField;
        
        private string new_contactoField;
        
        private string new_contactoidField;
        
        private string new_idField;
        
        private string new_nameField;
        
        private string new_razonsocialField;
        
        private string new_rfcField;
        
        private string new_direccionfiscalcalleynumeroField;
        
        private string new_recr_codigopostalField;
        
        private string new_direccionfiscalcoloniaField;
        
        private string new_direccionfiscalestadoField;
        
        private string new_direccionfiscalmunicipioField;
        
        private string new_direccionfiscalpaisField;
        
        private string new_observacionesField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string new_datosfiscalesdecontactoid {
            get {
                return this.new_datosfiscalesdecontactoidField;
            }
            set {
                this.new_datosfiscalesdecontactoidField = value;
            }
        }
        
        /// <remarks/>
        public string new_contacto {
            get {
                return this.new_contactoField;
            }
            set {
                this.new_contactoField = value;
            }
        }
        
        /// <remarks/>
        public string new_contactoid {
            get {
                return this.new_contactoidField;
            }
            set {
                this.new_contactoidField = value;
            }
        }
        
        /// <remarks/>
        public string new_id {
            get {
                return this.new_idField;
            }
            set {
                this.new_idField = value;
            }
        }
        
        /// <remarks/>
        public string new_name {
            get {
                return this.new_nameField;
            }
            set {
                this.new_nameField = value;
            }
        }
        
        /// <remarks/>
        public string new_razonsocial {
            get {
                return this.new_razonsocialField;
            }
            set {
                this.new_razonsocialField = value;
            }
        }
        
        /// <remarks/>
        public string new_rfc {
            get {
                return this.new_rfcField;
            }
            set {
                this.new_rfcField = value;
            }
        }
        
        /// <remarks/>
        public string new_direccionfiscalcalleynumero {
            get {
                return this.new_direccionfiscalcalleynumeroField;
            }
            set {
                this.new_direccionfiscalcalleynumeroField = value;
            }
        }
        
        /// <remarks/>
        public string new_recr_codigopostal {
            get {
                return this.new_recr_codigopostalField;
            }
            set {
                this.new_recr_codigopostalField = value;
            }
        }
        
        /// <remarks/>
        public string new_direccionfiscalcolonia {
            get {
                return this.new_direccionfiscalcoloniaField;
            }
            set {
                this.new_direccionfiscalcoloniaField = value;
            }
        }
        
        /// <remarks/>
        public string new_direccionfiscalestado {
            get {
                return this.new_direccionfiscalestadoField;
            }
            set {
                this.new_direccionfiscalestadoField = value;
            }
        }
        
        /// <remarks/>
        public string new_direccionfiscalmunicipio {
            get {
                return this.new_direccionfiscalmunicipioField;
            }
            set {
                this.new_direccionfiscalmunicipioField = value;
            }
        }
        
        /// <remarks/>
        public string new_direccionfiscalpais {
            get {
                return this.new_direccionfiscalpaisField;
            }
            set {
                this.new_direccionfiscalpaisField = value;
            }
        }
        
        /// <remarks/>
        public string new_observaciones {
            get {
                return this.new_observacionesField;
            }
            set {
                this.new_observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsDatosFiscalesCompletedEventHandler(object sender, ConsDatosFiscalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsDatosFiscalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsDatosFiscalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsDatosFiscales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsDatosFiscales[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsDatosFiscalesGuidCompletedEventHandler(object sender, ConsDatosFiscalesGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsDatosFiscalesGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsDatosFiscalesGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsDatosFiscales[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsDatosFiscales[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591