//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_InsertaDatosFiscalesContacto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_InsertaDatosFiscalesContactoSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_InsertaDatosFiscalesContacto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsDatosFiscalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsDatosFiscalesIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_InsertaDatosFiscalesContacto() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_InsertaDatosFiscalesContacto_WS_LE_InsertaDatosFiscalesContacto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsDatosFiscalesCompletedEventHandler InsDatosFiscalesCompleted;
        
        /// <remarks/>
        public event InsDatosFiscalesIDCompletedEventHandler InsDatosFiscalesIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsDatosFiscales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta InsDatosFiscales(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones) {
            object[] results = this.Invoke("InsDatosFiscales", new object[] {
                        new_contacto,
                        new_id,
                        new_name,
                        new_razonsocial,
                        new_rfc,
                        new_direccionfiscalpais,
                        new_direccionfiscalestado,
                        new_direccionfiscalmunicipio,
                        new_direccionfiscalcolonia,
                        new_direccionfiscalcalleynumero,
                        new_direccionfiscalcodigopostal,
                        new_recr_codigopostal,
                        new_observaciones});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void InsDatosFiscalesAsync(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones) {
            this.InsDatosFiscalesAsync(new_contacto, new_id, new_name, new_razonsocial, new_rfc, new_direccionfiscalpais, new_direccionfiscalestado, new_direccionfiscalmunicipio, new_direccionfiscalcolonia, new_direccionfiscalcalleynumero, new_direccionfiscalcodigopostal, new_recr_codigopostal, new_observaciones, null);
        }
        
        /// <remarks/>
        public void InsDatosFiscalesAsync(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones, object userState) {
            if ((this.InsDatosFiscalesOperationCompleted == null)) {
                this.InsDatosFiscalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsDatosFiscalesOperationCompleted);
            }
            this.InvokeAsync("InsDatosFiscales", new object[] {
                        new_contacto,
                        new_id,
                        new_name,
                        new_razonsocial,
                        new_rfc,
                        new_direccionfiscalpais,
                        new_direccionfiscalestado,
                        new_direccionfiscalmunicipio,
                        new_direccionfiscalcolonia,
                        new_direccionfiscalcalleynumero,
                        new_direccionfiscalcodigopostal,
                        new_recr_codigopostal,
                        new_observaciones}, this.InsDatosFiscalesOperationCompleted, userState);
        }
        
        private void OnInsDatosFiscalesOperationCompleted(object arg) {
            if ((this.InsDatosFiscalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsDatosFiscalesCompleted(this, new InsDatosFiscalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsDatosFiscalesID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta InsDatosFiscalesID(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones, string dummy) {
            object[] results = this.Invoke("InsDatosFiscalesID", new object[] {
                        new_contacto,
                        new_id,
                        new_name,
                        new_razonsocial,
                        new_rfc,
                        new_direccionfiscalpais,
                        new_direccionfiscalestado,
                        new_direccionfiscalmunicipio,
                        new_direccionfiscalcolonia,
                        new_direccionfiscalcalleynumero,
                        new_direccionfiscalcodigopostal,
                        new_recr_codigopostal,
                        new_observaciones,
                        dummy});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void InsDatosFiscalesIDAsync(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones, string dummy) {
            this.InsDatosFiscalesIDAsync(new_contacto, new_id, new_name, new_razonsocial, new_rfc, new_direccionfiscalpais, new_direccionfiscalestado, new_direccionfiscalmunicipio, new_direccionfiscalcolonia, new_direccionfiscalcalleynumero, new_direccionfiscalcodigopostal, new_recr_codigopostal, new_observaciones, dummy, null);
        }
        
        /// <remarks/>
        public void InsDatosFiscalesIDAsync(string new_contacto, string new_id, string new_name, string new_razonsocial, string new_rfc, string new_direccionfiscalpais, string new_direccionfiscalestado, string new_direccionfiscalmunicipio, string new_direccionfiscalcolonia, string new_direccionfiscalcalleynumero, string new_direccionfiscalcodigopostal, string new_recr_codigopostal, string new_observaciones, string dummy, object userState) {
            if ((this.InsDatosFiscalesIDOperationCompleted == null)) {
                this.InsDatosFiscalesIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsDatosFiscalesIDOperationCompleted);
            }
            this.InvokeAsync("InsDatosFiscalesID", new object[] {
                        new_contacto,
                        new_id,
                        new_name,
                        new_razonsocial,
                        new_rfc,
                        new_direccionfiscalpais,
                        new_direccionfiscalestado,
                        new_direccionfiscalmunicipio,
                        new_direccionfiscalcolonia,
                        new_direccionfiscalcalleynumero,
                        new_direccionfiscalcodigopostal,
                        new_recr_codigopostal,
                        new_observaciones,
                        dummy}, this.InsDatosFiscalesIDOperationCompleted, userState);
        }
        
        private void OnInsDatosFiscalesIDOperationCompleted(object arg) {
            if ((this.InsDatosFiscalesIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsDatosFiscalesIDCompleted(this, new InsDatosFiscalesIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta {
        
        private string codigoMsField;
        
        private string mensajeField;
        
        private string guidField;
        
        /// <remarks/>
        public string CodigoMs {
            get {
                return this.codigoMsField;
            }
            set {
                this.codigoMsField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsDatosFiscalesCompletedEventHandler(object sender, InsDatosFiscalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsDatosFiscalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsDatosFiscalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsDatosFiscalesIDCompletedEventHandler(object sender, InsDatosFiscalesIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsDatosFiscalesIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsDatosFiscalesIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591