//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLegadoEducativo02.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_ClientePotencial_LE/WS_LE_I" +
            "nsertaClientePotencial.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaClientePotencial_WS_LE_InsertaClientePotencial {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaClientePotencial_WS_LE_InsertaClientePotencial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_InsUs" +
            "uarioExterno.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsUsuarioExterno_WS_LE_InsUsuarioExterno {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsUsuarioExterno_WS_LE_InsUsuarioExterno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConsU" +
            "suext.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsUsuext_WS_LE_ConsUsuext {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsUsuext_WS_LE_ConsUsuext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConsC" +
            "P.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsCP_WS_LE_ConsCP {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsCP_WS_LE_ConsCP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_DatosFiscalesContacto_LE/WS" +
            "_LE_InsertaDatosFiscalesContacto.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaDatosFiscalesContacto_WS_LE_InsertaDatosFiscalesContacto {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaDatosFiscalesContacto_WS_LE_InsertaDatosFiscale" +
                    "sContacto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_InsertaFamilia_LE/WS_LE_Ins" +
            "ertaFamilia.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaFamilia_WS_LE_InsertaFamilia {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaFamilia_WS_LE_InsertaFamilia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConsN" +
            "ivelAcademico.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsNivelAcademico_WS_LE_ConsNivelAcademico {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsNivelAcademico_WS_LE_ConsNivelAcademico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_Contactos_LE/WS_LE_InsertaC" +
            "ontactos.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaContactos_WS_LE_InsertaContactos {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaContactos_WS_LE_InsertaContactos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_Consu" +
            "ltaContac.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsultaContac_WS_LE_ConsultaContac {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsultaContac_WS_LE_ConsultaContac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_Oportunidad_LE/WS_LE_Oportu" +
            "nidad.asmx")]
        public string WebLegadoEducativo02_WS_LE_Oportunidad_WS_LE_Oportunidad {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_Oportunidad_WS_LE_Oportunidad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConsE" +
            "scuelaCuenta.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsEscuelaCuenta_WS_LE_ConsEscuelaCuenta {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsEscuelaCuenta_WS_LE_ConsEscuelaCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConCl" +
            "ientePotencial.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConClientePotencial_WS_LE_ConClientePotencial {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConClientePotencial_WS_LE_ConClientePotencial"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_LegadoEducativo/WS_LE_ConsF" +
            "uenteLead.asmx")]
        public string WebLegadoEducativo02_WS_LE_ConsFuenteLead_WS_LE_ConsFuenteLead {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_ConsFuenteLead_WS_LE_ConsFuenteLead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/DesarrolloUDEM/Legado%20Educativo/WS_SolicitudCompra_LE/WS_LE_In" +
            "sertaSolicitudCom.asmx")]
        public string WebLegadoEducativo02_WS_LE_InsertaSolicitudCom_WS_LE_InsertaSolicitudCom {
            get {
                return ((string)(this["WebLegadoEducativo02_WS_LE_InsertaSolicitudCom_WS_LE_InsertaSolicitudCom"]));
            }
        }
    }
}
