//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_Beneficiarios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_BeneficiariosSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_Beneficiarios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsBeneficiarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_Beneficiarios() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_Beneficiarios_WS_LE_Beneficiarios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsBeneficiarioCompletedEventHandler InsBeneficiarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsBeneficiario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta InsBeneficiario(string udem_solicituddecompra, string udem_beneficiario, string udem_niveldeestudio, string udem_escueladeprocedencia, string udem_carreranoudem, string udem_grado, string udem_debeca) {
            object[] results = this.Invoke("InsBeneficiario", new object[] {
                        udem_solicituddecompra,
                        udem_beneficiario,
                        udem_niveldeestudio,
                        udem_escueladeprocedencia,
                        udem_carreranoudem,
                        udem_grado,
                        udem_debeca});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void InsBeneficiarioAsync(string udem_solicituddecompra, string udem_beneficiario, string udem_niveldeestudio, string udem_escueladeprocedencia, string udem_carreranoudem, string udem_grado, string udem_debeca) {
            this.InsBeneficiarioAsync(udem_solicituddecompra, udem_beneficiario, udem_niveldeestudio, udem_escueladeprocedencia, udem_carreranoudem, udem_grado, udem_debeca, null);
        }
        
        /// <remarks/>
        public void InsBeneficiarioAsync(string udem_solicituddecompra, string udem_beneficiario, string udem_niveldeestudio, string udem_escueladeprocedencia, string udem_carreranoudem, string udem_grado, string udem_debeca, object userState) {
            if ((this.InsBeneficiarioOperationCompleted == null)) {
                this.InsBeneficiarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsBeneficiarioOperationCompleted);
            }
            this.InvokeAsync("InsBeneficiario", new object[] {
                        udem_solicituddecompra,
                        udem_beneficiario,
                        udem_niveldeestudio,
                        udem_escueladeprocedencia,
                        udem_carreranoudem,
                        udem_grado,
                        udem_debeca}, this.InsBeneficiarioOperationCompleted, userState);
        }
        
        private void OnInsBeneficiarioOperationCompleted(object arg) {
            if ((this.InsBeneficiarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsBeneficiarioCompleted(this, new InsBeneficiarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Respuesta {
        
        private string codigoMsField;
        
        private string mensajeField;
        
        private string guidField;
        
        /// <remarks/>
        public string CodigoMs {
            get {
                return this.codigoMsField;
            }
            set {
                this.codigoMsField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsBeneficiarioCompletedEventHandler(object sender, InsBeneficiarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsBeneficiarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsBeneficiarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591