//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ConsFamiliaContacto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ConsFamiliaContactoSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ConsFamiliaContacto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsFamOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsFamParentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ConsFamiliaContacto() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ConsFamiliaContacto_WS_LE_ConsFamiliaContacto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsFamCompletedEventHandler ConsFamCompleted;
        
        /// <remarks/>
        public event ConsFamParentCompletedEventHandler ConsFamParentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsFam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsFamiliaContacto[] ConsFam(string Guidfam) {
            object[] results = this.Invoke("ConsFam", new object[] {
                        Guidfam});
            return ((CsFamiliaContacto[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsFamAsync(string Guidfam) {
            this.ConsFamAsync(Guidfam, null);
        }
        
        /// <remarks/>
        public void ConsFamAsync(string Guidfam, object userState) {
            if ((this.ConsFamOperationCompleted == null)) {
                this.ConsFamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsFamOperationCompleted);
            }
            this.InvokeAsync("ConsFam", new object[] {
                        Guidfam}, this.ConsFamOperationCompleted, userState);
        }
        
        private void OnConsFamOperationCompleted(object arg) {
            if ((this.ConsFamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsFamCompleted(this, new ConsFamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsFamParent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsFamiliaContacto[] ConsFamParent(string contactid, string familiarId) {
            object[] results = this.Invoke("ConsFamParent", new object[] {
                        contactid,
                        familiarId});
            return ((CsFamiliaContacto[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsFamParentAsync(string contactid, string familiarId) {
            this.ConsFamParentAsync(contactid, familiarId, null);
        }
        
        /// <remarks/>
        public void ConsFamParentAsync(string contactid, string familiarId, object userState) {
            if ((this.ConsFamParentOperationCompleted == null)) {
                this.ConsFamParentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsFamParentOperationCompleted);
            }
            this.InvokeAsync("ConsFamParent", new object[] {
                        contactid,
                        familiarId}, this.ConsFamParentOperationCompleted, userState);
        }
        
        private void OnConsFamParentOperationCompleted(object arg) {
            if ((this.ConsFamParentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsFamParentCompleted(this, new ConsFamParentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsFamiliaContacto {
        
        private string new_idField;
        
        private string new_nameField;
        
        private string new_contactoField;
        
        private string recr_familiaridField;
        
        private string new_familiarField;
        
        private string new_parentescoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string new_id {
            get {
                return this.new_idField;
            }
            set {
                this.new_idField = value;
            }
        }
        
        /// <remarks/>
        public string new_name {
            get {
                return this.new_nameField;
            }
            set {
                this.new_nameField = value;
            }
        }
        
        /// <remarks/>
        public string new_contacto {
            get {
                return this.new_contactoField;
            }
            set {
                this.new_contactoField = value;
            }
        }
        
        /// <remarks/>
        public string recr_familiarid {
            get {
                return this.recr_familiaridField;
            }
            set {
                this.recr_familiaridField = value;
            }
        }
        
        /// <remarks/>
        public string new_familiar {
            get {
                return this.new_familiarField;
            }
            set {
                this.new_familiarField = value;
            }
        }
        
        /// <remarks/>
        public string new_parentesco {
            get {
                return this.new_parentescoField;
            }
            set {
                this.new_parentescoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsFamCompletedEventHandler(object sender, ConsFamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsFamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsFamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsFamiliaContacto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsFamiliaContacto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsFamParentCompletedEventHandler(object sender, ConsFamParentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsFamParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsFamParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsFamiliaContacto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsFamiliaContacto[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591