//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebLegadoEducativo02.WS_LE_ListaDePrecios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_LE_ListaDePreciosSoap", Namespace="http://tempuri.org/")]
    public partial class WS_LE_ListaDePrecios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsListaPreciosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_LE_ListaDePrecios() {
            this.Url = global::WebLegadoEducativo02.Properties.Settings.Default.WebLegadoEducativo02_WS_LE_ListaDePrecios_WS_LE_ListaDePrecios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsListaPreciosCompletedEventHandler ConsListaPreciosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsListaPrecios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CsListaDePrecios[] ConsListaPrecios(string guidListaDePrecios) {
            object[] results = this.Invoke("ConsListaPrecios", new object[] {
                        guidListaDePrecios});
            return ((CsListaDePrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsListaPreciosAsync(string guidListaDePrecios) {
            this.ConsListaPreciosAsync(guidListaDePrecios, null);
        }
        
        /// <remarks/>
        public void ConsListaPreciosAsync(string guidListaDePrecios, object userState) {
            if ((this.ConsListaPreciosOperationCompleted == null)) {
                this.ConsListaPreciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsListaPreciosOperationCompleted);
            }
            this.InvokeAsync("ConsListaPrecios", new object[] {
                        guidListaDePrecios}, this.ConsListaPreciosOperationCompleted, userState);
        }
        
        private void OnConsListaPreciosOperationCompleted(object arg) {
            if ((this.ConsListaPreciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsListaPreciosCompleted(this, new ConsListaPreciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CsListaDePrecios {
        
        private string productpricelevelidField;
        
        private string pricelevelidField;
        
        private string pricelevel_nameField;
        
        private string productidField;
        
        private string product_nameField;
        
        private string uomidField;
        
        private string uom_nameField;
        
        private string transactioncurrencyidField;
        
        private string transactioncurrency_nameField;
        
        private string quantitysellingcodeField;
        
        private string pricingmethodcodeField;
        
        private string amountField;
        
        private string percentageField;
        
        private string roundingpolicycodeField;
        
        private string roundingoptioncodeField;
        
        private string roundingoptionamountField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string productpricelevelid {
            get {
                return this.productpricelevelidField;
            }
            set {
                this.productpricelevelidField = value;
            }
        }
        
        /// <remarks/>
        public string pricelevelid {
            get {
                return this.pricelevelidField;
            }
            set {
                this.pricelevelidField = value;
            }
        }
        
        /// <remarks/>
        public string pricelevel_name {
            get {
                return this.pricelevel_nameField;
            }
            set {
                this.pricelevel_nameField = value;
            }
        }
        
        /// <remarks/>
        public string productid {
            get {
                return this.productidField;
            }
            set {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                this.product_nameField = value;
            }
        }
        
        /// <remarks/>
        public string uomid {
            get {
                return this.uomidField;
            }
            set {
                this.uomidField = value;
            }
        }
        
        /// <remarks/>
        public string uom_name {
            get {
                return this.uom_nameField;
            }
            set {
                this.uom_nameField = value;
            }
        }
        
        /// <remarks/>
        public string transactioncurrencyid {
            get {
                return this.transactioncurrencyidField;
            }
            set {
                this.transactioncurrencyidField = value;
            }
        }
        
        /// <remarks/>
        public string transactioncurrency_name {
            get {
                return this.transactioncurrency_nameField;
            }
            set {
                this.transactioncurrency_nameField = value;
            }
        }
        
        /// <remarks/>
        public string quantitysellingcode {
            get {
                return this.quantitysellingcodeField;
            }
            set {
                this.quantitysellingcodeField = value;
            }
        }
        
        /// <remarks/>
        public string pricingmethodcode {
            get {
                return this.pricingmethodcodeField;
            }
            set {
                this.pricingmethodcodeField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string percentage {
            get {
                return this.percentageField;
            }
            set {
                this.percentageField = value;
            }
        }
        
        /// <remarks/>
        public string roundingpolicycode {
            get {
                return this.roundingpolicycodeField;
            }
            set {
                this.roundingpolicycodeField = value;
            }
        }
        
        /// <remarks/>
        public string roundingoptioncode {
            get {
                return this.roundingoptioncodeField;
            }
            set {
                this.roundingoptioncodeField = value;
            }
        }
        
        /// <remarks/>
        public string roundingoptionamount {
            get {
                return this.roundingoptionamountField;
            }
            set {
                this.roundingoptionamountField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsListaPreciosCompletedEventHandler(object sender, ConsListaPreciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsListaPreciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsListaPreciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CsListaDePrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CsListaDePrecios[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591